### ISSUE TITLE
ModuleNotFoundError: No module named 'rbflayer'

### ISSUE THREAD

**Issue by anubhav0296** [PetraVidnerova/rbf_keras#14]
I have tried importing rbflayer using pip install rbflayer but it is still showing same error.Please help.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-da12e0140e0e> in <module>
      4 # from keras.optimizers import RMSprop
      5 from tensorflow.keras.optimizers import RMSprop
----> 6 from rbflayer import RBFLayer, InitCentersRandom
      7 import matplotlib.pyplot as plt
      8 

ModuleNotFoundError: No module named 'rbflayer'

Please provide your mail id on shanukumar.srivastava77@gmail.com so that i can further elaborate my problem.

**Comment by PetraVidnerova** [comment]
you have to put the path to your rbf_keras directory to your python path
