### ISSUE TITLE
Use rbf layer on top of other dense or cnn layers

### ISSUE THREAD

**Issue by jcpeterson** [PetraVidnerova/rbf_keras#6]
I'd like to apply this layer to an existing network, but `InitCentersRandom(X)` requires a dataset, e.g., `X`, instead of just inferring the shape from the previous input layer. Is a more general implementation of this layer planned?

**Comment by jcpeterson** [comment]
Looks like this would work: https://stackoverflow.com/questions/53855941/how-to-implement-rbf-activation-function-in-keras

**Comment by PetraVidnerova** [comment]
You may want to see https://github.com/PetraVidnerova/rbf_tests/blob/master/mnist_add_rbf.py where I used RBF layer on the top of an existing network. I didn't used InitCentersRandom, but the default RandomUniform initializer. However, you may need to add Normalization layer before RBFLayer to have initialized the centers correctly.
